Feature/news
19-20-1-PMi33/Lohyna-project pull request #108
Opened 2020-03-19 10:17 UTC by ZhavoronkovN

Added news and profile pages into project and they can accessed through home controller

2020-03-20 18:29 UTC, OlegAndrus12 commented
Actually, it`s ready to use. 
We shoud add services for this pages

2020-03-20 18:39 UTC, OlegAndrus12 approved these changes

2020-03-22 15:25 UTC, RomanLevkovych commented on WebApplication/Models/NewsViewModel.cs
> +namespace WebApplication.Models
Reformat to C# code standard

2020-03-22 15:25 UTC, RomanLevkovych commented on WebApplication/Models/Person.cs
> +    public class Person{
Move this to a separate project with folder:

Core.DTO <- Core is a project, DTO - folder.

WebApp models are used for forms and validation.

2020-03-22 15:25 UTC, RomanLevkovych commented on WebApplication/Models/ProfileViewModel.cs
> +    public class ProfileViewModel : AppViewModel{
ViewModel approach is not used in an ASP.NET application. 

Services approach is used: small classes that responsible for one thing. They are injected into controllers.
Create a separate project for this part.

2020-03-22 15:25 UTC, RomanLevkovych commented on Layouts/AdminPage/AdminDashboard.html
> +<!DOCTYPE html>
Remove layouts from the project.

Btw, it is not in development. Why is it in your project?

2020-03-22 15:25 UTC, RomanLevkovych commented on WebApplication/Controllers/HomeController.cs
> +            NewsViewModel nw = new NewsViewModel{User="Roman",NewsFeed=l};
This is not a ViewModel

2020-03-23 06:23 UTC, arihilmir requested changes
Don't implement two different tasks in one branch. Split them into 2.

2020-03-23 06:53 UTC, ZhavoronkovN commented on WebApplication/Models/ProfileViewModel.cs
> +    public class ProfileViewModel : AppViewModel{
Its not ViewModel, it is the model of exact view

2020-03-23 06:53 UTC, ZhavoronkovN commented on WebApplication/Models/Person.cs
> +    public class Person{
It was not the task

2020-03-23 06:54 UTC, ZhavoronkovN commented on WebApplication/Controllers/HomeController.cs
> +            NewsViewModel nw = new NewsViewModel{User="Roman",NewsFeed=l};
but model of view

2020-03-23 06:55 UTC, ZhavoronkovN commented on Layouts/AdminPage/AdminDashboard.html
> +<!DOCTYPE html>
what s wrong with doctype?

2020-03-23 07:23 UTC, RomanLevkovych commented on WebApplication/Models/Person.cs
> +    public class Person{
Actually, it is. You were to implement this part. As I said, WebApplication/Models stores models that used in forms. DTOs should be in separate place.

2020-03-23 07:23 UTC, RomanLevkovych commented on WebApplication/Models/ProfileViewModel.cs
> +    public class ProfileViewModel : AppViewModel{
Then choose a proper name and take a look at a comment above.

2020-03-23 07:24 UTC, RomanLevkovych commented on Layouts/AdminPage/AdminDashboard.html
> +<!DOCTYPE html>
There's nothing wrong with doctype. It is wrong to have folder from a branch with ongoing development.

2020-03-23 07:25 UTC, RomanLevkovych commented on WebApplication/Controllers/HomeController.cs
> +            NewsViewModel nw = new NewsViewModel{User="Roman",NewsFeed=l};
Then, why `Person` is not called `PersonViewModel`?

2020-04-23 06:50 UTC, closed without merging