News db
19-20-1-PMi33/Lohyna-project pull request #109
Opened 2020-03-22 15:49 UTC by RomanLevkovych

Storing news in db

No need in sharing db: use migrations. Minor architecture update.

2020-03-30 06:34 UTC, ZhavoronkovN commented on Model/LohynaDbContext.cs
> +    public class LohynaDbContext : DbContext
We use the name of app in code? What if we will change it? Probably use "AppDbContext"

2020-03-30 06:34 UTC, ZhavoronkovN commented on Model/Model.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Don`t we use core 3.0?

2020-03-30 06:39 UTC, ZhavoronkovN commented on Repositories/Persons/PersonRepository.cs
> +        public Person SearchLecturerById(int lecturerId)
Why don't return Lecturer?

2020-03-30 06:40 UTC, ZhavoronkovN commented on Repositories/Persons/PersonRepository.cs
> +        public async Task<int> CreatePersonAsync(Person person)
Do we need to create Person? Maybe this should be CreateLecturer?

2020-03-30 06:48 UTC, ZhavoronkovN commented on WebApplication/Startup.cs
> +                options.UseSqlite("Filename=/Users/roman_levkovych/Projects/Lohyna-project/university-db.db",
Don't this should be get from appsettings.json?

2020-03-30 06:49 UTC, ZhavoronkovN commented on WebApplication/appsettings.json
> +  "ResourcesDir": "/Users/roman_levkovych/Projects/Lohyna-project"
Don't commit your relative path

2020-03-30 06:54 UTC, nikilark requested changes
We need to organize images, stored in dbResources. Maybe use path like "bdResources/News/Images/smth.png"

2020-03-30 10:28 UTC, OlegAndrus12 commented on Model/Model.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Actually current asp.core version do not work on my machine.
I ought to change that to lower 3.0 version

2020-03-30 10:30 UTC, OlegAndrus12 commented on WebApplication/Startup.cs
> +                options.UseSqlite("Filename=/Users/roman_levkovych/Projects/Lohyna-project/university-db.db",
Do not store hardcoded path

2020-03-30 10:35 UTC, OlegAndrus12 commented on WebApplication/appsettings.json
> +  "ResourcesDir": "/Users/roman_levkovych/Projects/Lohyna-project"
+

2020-03-30 10:36 UTC, OlegAndrus12 commented
Should we add Lecturers and Students repositories, not only Person one?
Please, add CreateLecturerAsync method in Person repository.
What if we store images in wwwroot/Images ?

2020-03-30 10:40 UTC, OlegAndrus12 commented on Model/LohynaDbContext.cs
> +    public class LohynaDbContext : DbContext
I guess app name changing will not impact ridicioulsy on smth.
But in case of simplicity and clarity we should use name like "AppDbContext"

2020-03-30 10:42 UTC, OlegAndrus12 requested changes
Lorem ipsum

2020-03-30 12:36 UTC, RomanLevkovych commented on Model/Model.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
I don't know. Everything works for me. Ok, I'll change to 3.0

2020-04-05 17:57 UTC, RomanLevkovych commented
@OlegAndrus12 we shouldn't do this, because it is a web app static data. So, when the app is loaded in a browser, the content of the folder will be downloaded. This is not the desired behavior.

2020-04-22 07:11 UTC, nikilark approved these changes

2020-04-22 15:49 UTC, OlegAndrus12 approved these changes

2020-04-22 15:49 UTC, merged