Feature/profile asp
19-20-1-PMi33/Lohyna-project pull request #112
Opened 2020-04-05 09:20 UTC by ZhavoronkovN

Profile page is now accessible in application

2020-04-05 20:04 UTC, arihilmir commented on Core/DTO/Person.cs
> +    public enum PersonType{student,lecturer};
Format document according to C# Code Style

2020-04-05 20:04 UTC, arihilmir commented on .vscode/tasks.json
> +{
Remove your ide configs from the repository.

2020-04-05 20:04 UTC, arihilmir commented on Core/DTO/Student.cs
> +        public string Faculty {get; set; }
Format file

2020-04-05 20:04 UTC, RomanLevkovych commented on WebApplication/Models/ProfileViewModel.cs
> +    public class ProfileViewModel
Why do we need this class?

2020-04-05 20:04 UTC, RomanLevkovych commented on WebApplication/Controllers/ProfileController.cs
> +            ProfileViewModel model = new ProfileViewModel{
Change formatting.

2020-04-05 20:04 UTC, RomanLevkovych commented on WebApplication/Controllers/ProfileController.cs
> +                model.Name  = studentData.Name;
Why you don't return `studentData`? Or use the mapper.

2020-04-06 08:20 UTC, RomanLevkovych commented on WebApplication/Controllers/ProfileController.cs
> +            _mapper = mapper;
Decide what mapper to use.

2020-04-06 08:51 UTC, ZhavoronkovN commented on WebApplication/Controllers/ProfileController.cs
> +            _mapper = mapper;
Both with different purposes?

2020-04-06 09:25 UTC, OlegAndrus12 requested changes

2020-04-06 09:25 UTC, OlegAndrus12 commented on WebApplication/Models/ProfileViewModel.cs
> +    public class ProfileViewModel
plus. 
@RomanLevkovych said that in WebApp/Models we write only extra classes for forms data

2020-04-06 09:25 UTC, OlegAndrus12 commented on WebApplication/Views/Profile/Profile.cshtml
> +      <h4 class="mb-n3 block-title ml-3 px-2">Latest achievments :</h4>
What about achievements.
Should we store that in bd?

2020-04-06 09:25 UTC, OlegAndrus12 commented on WebApplication/Views/Profile/Profile.cshtml
> +      <h4 class="mb-n3 block-title ml-3 px-2">Probably can be found at :</h4>
This should work or be removed at all.
Do you have any idea how to organize that?

2020-04-06 09:25 UTC, OlegAndrus12 commented on WebApplication/wwwroot/css/site.css
> -﻿/* Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
If you`re going to write all CSS code in one css file, please, add some structure using comments.
I think it would be better to manage separate css file to separate html file.

2020-04-06 17:21 UTC, ZhavoronkovN commented on WebApplication/wwwroot/css/site.css
> -﻿/* Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
What for? Comments are created to help people understand code, but not to add structure
What is more, I think discussing about css files design is not related to this pull request

2020-04-06 17:23 UTC, ZhavoronkovN commented on WebApplication/Views/Profile/Profile.cshtml
> +      <h4 class="mb-n3 block-title ml-3 px-2">Probably can be found at :</h4>
Remove what? Organize what? Please be specific, because now it looks like you offer me to remove two closing div`s, one opened and one h4

2020-04-06 17:23 UTC, ZhavoronkovN commented on WebApplication/Views/Profile/Profile.cshtml
> +      <h4 class="mb-n3 block-title ml-3 px-2">Latest achievments :</h4>
We are so far away from this
But yes, achievments would be in bd

2020-04-06 20:16 UTC, arihilmir commented on WebApplication/Controllers/ProfileController.cs
> +            _mapper = mapper;
Do you use `_mapper` in code?

2020-04-07 12:34 UTC, OlegAndrus12 commented on WebApplication/Views/Profile/Profile.cshtml
> +      <h4 class="mb-n3 block-title ml-3 px-2">Probably can be found at :</h4>
Ми не зберігаємо у базі аудиторій.
Як тоді відслідковувати місцезнаходження юзера?

2020-04-07 12:36 UTC, OlegAndrus12 commented on WebApplication/wwwroot/css/site.css
> -﻿/* Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
Якщо увесь CSS знаходитметься в одному файлі, то потім буде складно знайти до якої сторінки, який кусок коду належить. Тому я пропоную або відділяти за допомогою коментів код специфічний для конкретної сторінки  або ж одразу розділяти стилі по різним файлам

2020-04-12 13:56 UTC, OlegAndrus12 approved these changes
Merge this, sir

2020-04-13 06:17 UTC, merged