News feed impl.
19-20-1-PMi33/Lohyna-project pull request #113
Opened 2020-04-22 07:13 UTC by RomanLevkovych

2020-04-22 08:40 UTC, OlegAndrus12 requested changes

2020-04-22 08:40 UTC, OlegAndrus12 commented on WebApplication/Controllers/HomeController.cs
> -        public HomeController(IMapper mapper, INewsFeedService newsFeed, ILogger<HomeController> logger)
We refused to use logger?

2020-04-22 08:40 UTC, OlegAndrus12 commented on WebApplication/Controllers/HomeController.cs
> +        private string EncodeImage(string path)
I guess we need such method in any page, where we works with images.
Maybe make it public and static?

2020-04-22 08:43 UTC, ZhavoronkovN commented on WebApplication/Controllers/HomeController.cs
> +        private string EncodeImage(string path)
I am not sure that encoding images is work for home controller. We could add method like this somewhere in admin page part to upload photos to database. And for now we can use some online services to convert images to base64

2020-04-22 08:49 UTC, ZhavoronkovN commented on WebApplication/Views/Home/Index.cshtml
> +@foreach (var n in Model)
please replace "n" with something more meaningful

2020-04-22 09:03 UTC, RomanLevkovych commented on WebApplication/Controllers/HomeController.cs
> +        private string EncodeImage(string path)
We can move it to Core as ImageHelper.

2020-04-22 09:03 UTC, ZhavoronkovN commented on WebApplication/Views/Home/Index.cshtml
> +    <link rel="stylesheet" href="~/css/local.css" />
local.css?
maybe use something more like "newsPageStyles.css"?

2020-04-22 09:03 UTC, RomanLevkovych commented on WebApplication/Controllers/HomeController.cs
> -        public HomeController(IMapper mapper, INewsFeedService newsFeed, ILogger<HomeController> logger)
Well, we don't use it here, so it can be safely removed from here.

2020-04-23 06:53 UTC, nikilark approved these changes

2020-04-23 06:55 UTC, OlegAndrus12 approved these changes

2020-04-26 10:05 UTC, merged