Feature/profile vm2
19-20-1-PMi33/Lohyna-project pull request #62
Opened 2019-11-26 10:31 UTC by OlegAndrus12

Autorized lecturer and student are tested.
We ought to change design, cause profile page looks very poor for lecturer.
Sould we add service for getting lecturer knowing mark

2019-11-26 14:22 UTC, RomanLevkovych commented on DataServices/SqliteDbContext.cs
> +            connectionStringBuilder.DataSource = @"C:\Users\andru\Documents\GitHub\Lohyna-project\DataServices\univerity-db.db";
Remove this from commit, please

2019-11-26 14:22 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +            this.logic = new ProfilePageVM(new SQLiteDataService(), "LubomyrHalamaga");
why user is hardcoded?

2019-11-26 14:22 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +        private void Content_Button_prev_MouseDown(object sender, MouseButtonEventArgs e)
Please, leave meaningful names for your methods, not generated one

2019-11-26 14:22 UTC, RomanLevkovych commented on View/Widgets/ProfilePageContent.xaml
> +        <TextBlock x:Name="label3" Text="Nom zal : " Grid.Row="4" Grid.Column="2" VerticalAlignment="Center" FontSize="22" Margin="10 0 0 0"/>
The same for names. If you youse a name - give it a meaningful name, otherwise - remove it

2019-11-26 14:22 UTC, RomanLevkovych commented on View/Widgets/ProfilePageTableMarksHead.xaml
> +        <Button x:Name="semester_column" Grid.Column="3" Content="Semester" FontSize="20" Cursor="Hand" Style="{StaticResource HeaderRowButton}"/>
No underscores as word-separator, only C(c)amelCase.

2019-11-26 14:22 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +            return currentPageMarks;
camelCase

2019-11-26 14:22 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +        public ProfilePageVM(SQLiteDataService dataService, string username)
You have to use appropriate service in ctor of VM

2019-11-26 14:22 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +            this.username = username;
`this` is redundant here.

2019-12-03 19:56 UTC, nikilark approved these changes

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +                temp.UriSource = new Uri("C:/Users/andru/Documents/GitHub/Lohyna-project/View/Widgets/Images/profile_placeholder.jpg", UriKind.Relative);
Don't use hardware or software specific data/calls. Use standard language structures for this.

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +                    content.groupDepartmentTextblock.Text = $"{logic.GetLecturer().Department}";
Do we really need to wrap it in a string literal?

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +                    content.numberZalikovkaTextblock.Text = $"{logic.GetStudent().TicketNumber}";
The same

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +                    this.content.marks.stack2.Children.Add(item);
`this` is redundant here, remove it and prefere `var` over type specification.

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +        private void FillMarksTable()
Maybe, we should change the signature of this method to take a data for the table?

2019-12-06 19:48 UTC, RomanLevkovych commented on View/Widgets/ProfilePageTableMarksRow.xaml.cs
> +
Remove the empty method

2019-12-06 19:48 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +        public ProfilePageVM(SQLiteDataService dataService, string username)
It hasn't been fixed yet.

2019-12-06 19:48 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +        private List<Rating> currentPageMarks;
Probably, we should convert this field to internal value field of method?

2019-12-06 19:48 UTC, RomanLevkovych commented on ViewModel/ProfilePageVM.cs
> +                currentPageMarks = marks.GetRange(currentPageNumber * pageLimit, marks.Count % pageLimit);
Remove these ifs. Introduce variable for end of range and init it from ternary operator

2019-12-06 20:02 UTC, OlegAndrus12 commented on View/Pages/ProfilePage.xaml.cs
> +                    content.groupDepartmentTextblock.Text = $"{logic.GetLecturer().Department}";
Does it really matters?

2019-12-06 20:03 UTC, RomanLevkovych commented on View/Pages/ProfilePage.xaml.cs
> +                    content.groupDepartmentTextblock.Text = $"{logic.GetLecturer().Department}";
Yes

2019-12-06 20:03 UTC, ungidrid requested changes

2019-12-06 20:03 UTC, ungidrid commented on DataServices/SqliteDbContext.cs
> +            connectionStringBuilder.DataSource = @"..\..\..\..\DataServices\university-db.db";
Use normal sql connection string, not path to do file

2019-12-06 20:03 UTC, ungidrid commented on View/Pages/ProfilePage.xaml.cs
> +        int current_page_number = 0;
Use camelCase

2019-12-06 20:03 UTC, ungidrid commented on View/Pages/ProfilePage.xaml.cs
> +                sorted = SortMarkTable.MarkReverse;
Put enum value into local variable using ternary operator so to make your code DRY

2019-12-06 20:08 UTC, OlegAndrus12 commented on DataServices/DataServiceBase.cs
> +            return _dataSource.Student.SingleOrDefault(p => p.Person.Username == person.Username);
Hmhmh...
Thanks, I`ll take it into consideration.
Den, it a joke or you really have to much free time to review other teams code?

2019-12-06 20:08 UTC, RomanLevkovych commented on DataServices/DataServiceBase.cs
> +            return _dataSource.Student.SingleOrDefault(p => p.Person.Username == person.Username);
I asked for this

2019-12-06 22:02 UTC, OlegAndrus12 commented
1) Normal connection string is the thing we are struggled with. Even in current version of development we do not use conString correctly. 
2) Do you know better way to save image, excluding BitmapImage?
3) How sholud looks path for image in db to work on any machine?
4) Other thing changed according to yours prepositions.

Thanks)

2019-12-07 13:45 UTC, OlegAndrus12 commented
I resolved problem with path using Directory.GetCurrenrDeirectory().
I think we can use this approach to conString in db.
Images in db shoud be stored in format Widgets\Images\photoName.png. (default falue in db for profile picture "Widgets\Images\profile_placeholder.jpg")

2019-12-09 14:48 UTC, merged