Feature/register vm
19-20-1-PMi33/Lohyna-project pull request #68
Opened 2019-12-08 09:19 UTC by Scaler358

Now we can register a new user!
Main feature is possibility to upload photo. Though, to do this you need to enter your student card number
The picture will store in chosen directory (now it Widgets/Images/Profile_Images) and have name equal to your student card to make them unique

2019-12-08 13:04 UTC, RomanLevkovych commented on View/Pages/RegisterPage.xaml.cs
> +            if (logic.validateValues(content.edit_Name.Text, content.edit_Surname.Text, content.edit_Zal.Text, content.edit_Username.Text, content.edit_Password.Password, content.edit_RepPassword.Pas
Simplify

2019-12-08 13:04 UTC, RomanLevkovych commented on View/Pages/RegisterPage.xaml.cs
> +        private RegisterPageVM logic;
Add more meaningful name to the field

2019-12-08 13:04 UTC, RomanLevkovych commented on ViewModel/RegisterPageVM.cs
> -    class RegisterPageVM
Add more meaningful name basing on the class responsibilities.

2019-12-08 13:21 UTC, Scaler358 commented on ViewModel/RegisterPageVM.cs
> -    class RegisterPageVM
But we call all ViewModel classes like that.
<joke>
(ValidatorCopiratorRegistratorDBConnectorForRegisterPage?)
</joke>

2019-12-08 16:58 UTC, OlegAndrus12 requested changes

2019-12-08 16:58 UTC, OlegAndrus12 commented on View/Pages/RegisterPage.xaml.cs
>          private void Content_Button_Register_Click(object sender, RoutedEventArgs e)
Use meaningful name, not the generated one for buttons actions.
+camelCase

2019-12-08 16:58 UTC, OlegAndrus12 commented on View/Pages/RegisterPage.xaml.cs
>              navbar.button_register.Click += LogInNavbar_Button_register_Click;
RegisterPageVM represent class responsibility correctly, as for me

2019-12-08 16:59 UTC, OlegAndrus12 commented on View/Widgets/RegisterPageContent.xaml
>          <TextBox x:Name="edit_Surname" Grid.Row="2" Grid.Column="5" Height="25" FontSize="18"></TextBox>
Camel

2019-12-09 07:44 UTC, Scaler358 commented on View/Pages/RegisterPage.xaml.cs
>          private void Content_Button_Register_Click(object sender, RoutedEventArgs e)
Can you look at this method and say what it doing? If yes, it is meaningful name

2019-12-09 13:31 UTC, OlegAndrus12 approved these changes

2019-12-09 13:50 UTC, merged